services:
  travels_backend:
    image: moriahs_travels-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    build:
      context: ./travels_frontend
    ports:
      - "19000:19000"
    networks:
      - travels-network

networks:
  travels-network:
    driver: bridge